version: '2'
# service
services:
  # php-apache
  php-apache:
    build: ./config/web
    ports:
      - '8080:80'
    volumes:
      - ./server:/var/www/html
    restart: always
    depends_on:
      - mysql

  # mysql
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    user: '1000:50'
    ports:
      - '3306:3306'
    volumes:
      - ./config/mysql/data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --innodb-use-native-aio=0
